baseURL = "https://jayaprakash-a.github.io/"
languageCode = "en-us"
title = "Jayaprakash Akula"
theme = ["personal-web"]
themesDir = "themes"

publishDir = "docs"

googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Jayaprakash:wave:"
  sub = "I'm a ML enthusiast"

[params.main]
  latestPublishHeader = "Welcome to my webpage!!"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/jayaprakash.jpg" # - default "/images/jayaprakash.jpg"

[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/jayaprakash-a/"
  twitter = "https://twitter.com/pra_jaya"
  linkedin = "https://www.linkedin.com/in/jayaprakash-akula-b40444126/"
  facebook = "https://www.facebook.com/jayaprakash.akula/"
  instagram = "https://www.instagram.com/jayaprakash_a/"
  mail = "mailto:akulajayaprakash [at] gmail [dot] com"



[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "education"
  name = "Education"
  title = "Education"
  url = "/education/"
  weight = -120

[[menu.main]]
  identifier = "internships"
  name = "My internships"
  title = "Experience section"
  url = "/internships/"
  weight = -120

[[menu.main]]
  identifier = "projects"
  name = "My projects"
  title = "Projects section"
  url = "/projects/"
  weight = -120

[[menu.main]]
  identifier = "publications"
  name = "My publications"
  title = "Publications section"
  url = "/publications/"
  weight = -120
